### ISSUE TITLE
How to move media files from root namespace to another internal namespace

### ISSUE THREAD

**Issue by MarcosMenegazzo** [michitux/dokuwiki-plugin-move#120]
Hello guys, 

I'm looking for a way to move media files from root namespace to another internal namespace, because these files were put there in the early stages of our wiki. The move plugin does a very good moving from one namespace to other, but I did find a way to select a media file from the tree, and give it a new name including a new namespace, like what can be done with pages. If I try to rename a media file in tree from "file" to "namespace:file", for example, the plugin replaces the ":" with "_". So, is there any way to achieve this?

**Comment by michitux** [comment]
You should be able to move the media file to an existing namespace using drag&drop, if you want to create a new namespace you can do this using the new namespace creation feature that was added in the most recent version of the move plugin.

**Comment by MarcosMenegazzo** [comment]
Sorry, I have not checked the docs saying that was possible to drag and drop. Thanks
