### ISSUE TITLE
Where is the Move/Rename button when using the `vector` template?

### ISSUE THREAD

**Issue by dougthor42** [michitux/dokuwiki-plugin-move#131]
I may just be blind, but I can't seem to find the move / rename button when using the vector template.

Is this an issue with the template or with the plugin? I'm not sure who I should submit the bug report to, sorry if this is the wrong place.

**Comment by Wesalius** [comment]
I have the same issue, I made sure the plugin is at lib/plugins/move/ but still no "move page button" appears

**Comment by helgator** [comment]
I use the bootstrap3 template and can't see the move button.

**Comment by splitbrain** [comment]
To quote the docs: "It is automatically available on all templates that implement the TEMPLATE_PAGETOOLS_DISPLAY event"
