### ISSUE TITLE
Dokuwiki "Greebo" support

### ISSUE THREAD

**Issue by dregad** [michitux/dokuwiki-plugin-move#147]
The plugin's _Rename page_ menu item is no longer available in the latest Dokuwiki release, as shown in the screenshots below

Frusterick Manners | Greebo
--- | ---
 ![move_plugin_frusterick](https://user-images.githubusercontent.com/449891/39172852-5499d59e-47a3-11e8-9b5e-df19155d79db.png) | ![move_plugin_greebo](https://user-images.githubusercontent.com/449891/39172851-5478167a-47a3-11e8-8c35-6f3bf312f6a0.png)

**Comment by dregad** [comment]
@michitux any idea when this could be done ? This is the only thing preventing me to upgrade 2 dokuwiki instances. Thanks in advance !

**Comment by micgro42** [comment]
I have increased the version and also adjusted the version number at DokuWiki.org. Though I do not see the problem with using the master branch, if you are using git anyway. Plugins are by default on a rolling release and the tip of the master branch is what you get when you install the plugin via DokuWiki's Extension Manager.
