### ISSUE TITLE
Add missing tags (and Github releases)

### ISSUE THREAD

**Issue by dregad** [michitux/dokuwiki-plugin-move#148]
I noticed that there are [only 3 tags](https://github.com/michitux/dokuwiki-plugin-move/tags) in the repo, while quite a few more versions were released according to git log.

Please find below a quick bash script to create the missing tags for the move plugin

```bash
# Loop over all commits where plugin info was changed
git log --format="%H|%ai"  -- plugin.info.txt |
    while IFS='|' read SHA GIT_COMMITER_DATE;
do
    # Retrieve release date from the commit's plugin.info.txt
    RELEASE_DATE=$(git show $SHA:plugin.info.txt |sed -n 's/^date *//p');

    # Skip commit if tag already exists
    [ $(git tag -l $RELEASE_DATE) ] && continue;

    git tag -a -m "Release $RELEASE_DATE" $RELEASE_DATE $SHA
done;
```

**Comment by splitbrain** [comment]
An alternative would be my script to automatically create new releases when stuff changes in master: https://www.patreon.com/posts/managing-plugin-8389933

**Comment by heylix** [comment]
@michitux can you create a new release? It seems the plugin's [page](https://www.dokuwiki.org/plugin:move) doesn't show the current release either.

Would be cool if we could roll back on problems.

**Comment by michitux** [comment]
I have added the missing tags and there are now GitHub releases for the most recent tags. I didn't bother to create GitHub releases for all tags. Also, I installed a workflow to automatically tag any future releases.
