### ISSUE TITLE
update documentation

### ISSUE THREAD

**Issue by splitbrain** [michitux/dokuwiki-plugin-move#15]
hey @michitux and @micgro42 I'd like to publish a little newsletter post on the hackfest soon and it will direct people to the plugin page. Could you update the page to reflect the new state of the plugin?

**Comment by michitux** [comment]
Thanks for the reminder, I'm not sure though if I'll find time for this before the weekend.

**Comment by splitbrain** [comment]
I updated the page with some minimal info on the new functionality. I'm don't remember if the events emitted by the plugin changed - the description might need to be adjusted. Also the feature description might not be uptodate.

**Comment by splitbrain** [comment]
this should be done by now
