### ISSUE TITLE
Tree based move doesn't allow move pages in an empty folder

### ISSUE THREAD

**Issue by TorMec** [michitux/dokuwiki-plugin-move#17]
Hi,
I'm trying to use the "tree based move" to move some pages into an empty folder which I've already created (permissions are read and write for all).

It seems to me that if the folder is empty it is not possible to move, with the drag & drop, any pages/folders inside it.

**Comment by polyzen** [comment]
:+1:

**Comment by samwilson** [comment]
How did you create the empty folder?

**Comment by TorMec** [comment]
Manually, taht is I go in /data/pages/../ and then right click and "create new folder".

If I use the form I can move folders/pages in this new empty folder, but I can't with the "tree based move"

**Comment by samwilson** [comment]
Oh, I was hoping you had some clever way of creating new folders through the web :)

**Comment by oscarmlage** [comment]
Just a question, how can I use the "Tree Move"? I've the last version of the plugin but I'm not able to see the Move Manager anywhere, I'm using last stable dokuwiki with Dokuwiki Template. I'm not able to see the "Simple Page Rename" side button neither, what should be wrong?
