### ISSUE TITLE
Too few arguments in rewrite.php on line 242 after updating to PHP 7.2

### ISSUE THREAD

**Issue by g-user** [michitux/dokuwiki-plugin-move#176]
With PHP 7.2  I got the error:

Fatal error: Uncaught ArgumentCountError: Too few arguments to function Doku_Parser::__construct(), 0 passed in /dokuwiki/lib/plugins/move/helper/rewrite.php on line 242 and exactly 1 expected in /dokuwiki/inc/parser/parser.php:53 

If I put in $Parser = new Doku_Parser(NULL); 
then I get:

Argument 1 passed to Doku_Parser::__construct() must be an instance of Doku_Handler, null given

I´m not so familiar with dokuwiki or move-plugin or PHP, but I read that PHP changed the behavior from >7.0 from "Warning" to "error" (Backward incompatible change)

Maybe this is the problem? How I can get an instance of Doku_Handler?

**Comment by phy25** [comment]
Are you using nightly version of DokuWiki? The internal API of the parser has a lot of changes so it is possible that a lot of modifications of this plugin is required.

I guess `$this->loadHelper('move_handler')`? However you may meet more issues afterwards.

**Comment by g-user** [comment]
Yes, I updated to the nightly dokuwiki version.
Your suggestion for the error was also my first try, but because I´m not familiar with PHP/dokuwiki I gave up and opened an issue.

The line
$Parser = new Doku_Parser($this->loadHelper('move_handler')); 
gives the following error:

Fatal error: Uncaught TypeError: Argument 1 passed to Doku_Parser::__construct() must be an instance of Doku_Handler, instance of helper_plugin_move_handler given, called in ...

**Comment by micgro42** [comment]
Apparently, we unintentionally broke backward compatibility there, I'm sorry.

I created a pull request (splitbrain/dokuwiki#2959) to Dokuwiki core that should hopefully fix this.
If you are using DokuWiki via git, could you try the branch `fixDoku_ParserCompat` and see if it improves the situation?

**Comment by g-user** [comment]
Hi micgro42,
I replaced the files parser.php and handler.php in /dokuwiki/inc/parser from your branch, but it doesn´t completely solves the problem.

I get 

Fatal error: Error, handler function finalize with 0 parameters called which isn't implemented in dokuwiki/lib/plugins/move/helper/handler.php on line 372

But the media and page files are copied ok (I move a complete namespace to a child of a different namespace), only the final link-rewriting isn´t done.

**Comment by g-user** [comment]
Additional test:
moving one namespace works as expected, if I change the line 377 in 
dokuwiki/lib/plugins/move/helper/handler.php

from 
   public function _finalize() # with underscore
to 
  public function finalize() # to w/o underscore

**Comment by micgro42** [comment]
Thank you for trying it out! I updated the pull request, could you try again? I'm hopeful that it works now 🙂

**Comment by g-user** [comment]
It´incedible, how fast you are!

I only take a look on your recent changes at the dokuwiki-code, I didn´t test it... But wouldn´t it be better to change the plugin code? Are your recent changes (in inc/Parsing/Parser.php) helpful for anything else than the move-plugin?  Or is it a "taint" of the dokuwiki-code only for one plugin?
I´m not in the position (lack of know how)  to judge it, it´s only a gut-feeling...

**Comment by micgro42** [comment]
Nah, the code base that caused this problem is just still fresh in my mind.

While the plugin code has to be adjusted eventually, we need to give the plugin authors some time to do that. Further, since DokuWiki unfortunately doesn't have proper version management for plugins, the plugins have to be compatible with both the stable and master branch of DokuWiki at the same time.

The move plugin is relatively important, but this change is likely to affect also other plugins. 
Finally, the move plugin is also complex and I don't know its code base that well. So it was faster for me to make the change in DokuWiki, in addition to it being the right place.

**Comment by g-user** [comment]
I did some tests moving pages and (also nested) namespaces - these were ok. So I will close the issue.

**Comment by micgro42** [comment]
Cool, thank you for testing!

But let's keep this issue open until that fix actually lands in DokuWiki master :)

**Comment by g-user** [comment]
pull request from micgro42 was merged to dokuwiki master with commit d4f6a7852c473169f2c3998e813e107bc6b0d9e0
