### ISSUE TITLE
PopUpViewer plugin support

### ISSUE THREAD

**Issue by richard-ostrochovsky** [michitux/dokuwiki-plugin-move#192]
please, wold it be possible to add support for this plugin?:

https://www.dokuwiki.org/plugin:popupviewer

(if you don't have the time, I could do it, if you'll give me some starting info)

thank you!

**Comment by richard-ostrochovsky** [comment]
made a christmas wish here: https://github.com/michitux/dokuwiki-plugin-move/issues/192

**Comment by richard-ostrochovsky** [comment]
this I did not find in documentation, but also this form of popup hyperlinks seems to be working:

{{popup>[[parent:child]]|clickable_text}}

or

{{popup>parent:child|clickable_text}}

not only (as documented)

{{popup>%parent:child%|clickable_text}}

As I see it, not all forms needs to be supported by movement, we could choose just one, which is easiest to implement, and recommend then that as best practise for PopUpViewer usage to be movable.

**Comment by phy25** [comment]
This is something that needs to be implemented in popupviewer, as move plugin already provides API for other plugins to do their move work: https://www.dokuwiki.org/plugin:move#support_for_other_plugins
