### ISSUE TITLE
embedover plugin support

### ISSUE THREAD

**Issue by richard-ostrochovsky** [michitux/dokuwiki-plugin-move#193]
please, wold it be possible to add support for this plugin?:

https://www.dokuwiki.org/plugin:embedover

(if you don't have the time, I could do it, if you'll give me some starting info)

thank you!

**Comment by phy25** [comment]
This is something that needs to be implemented in embedover, as move plugin already provides API for other plugins to do their move work: https://www.dokuwiki.org/plugin:move#support_for_other_plugins
