### ISSUE TITLE
Not compatible with PHP8

### ISSUE THREAD

**Issue by DeanCording** [michitux/dokuwiki-plugin-move#207]
PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /var/www/dokuwiki/lib/plugins/move/helper/handler.php on line 145

PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /var/www/dokuwiki/lib/plugins/move/helper/handler.php on line 176

$ php -v
PHP 8.0.8 (cli) (built: Sep 11 2021 04:17:39) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.8, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.8, Copyright (c), by Zend Technologies

Ubuntu 21.10

**Comment by gamma** [comment]
I had the same issue. Re-installing did fix it.

**Comment by michitux** [comment]
I've just updated the version so an update notice will be displayed.
