### ISSUE TITLE
Better handling for moving media.

### ISSUE THREAD

**Issue by racquetmaster** [michitux/dokuwiki-plugin-move#209]
It would be nice if there was a button added to the media manager for moving media similar to how pages are done. Not sure if the media manager is extendable or if this would require media manager changes.

**Comment by annda** [comment]
Moving media can be done in the move plugin itself. This is handled vey well by an calling [moveMedia()](https://github.com/michitux/dokuwiki-plugin-move/blob/dab956f98e23cdd63b3b1ee74d909132600ef88e/helper/op.php#L232), including link rewrites in existing wiki pages.

Some issues need special attention:

- ACL checks for the target file
- file overwrite check
- no change of file extension allowed!
- move history needs to be logged

**Comment by michitux** [comment]
This has been implemented in #246.
