### ISSUE TITLE
Include Plugin wants "adaptRelativeId" function in handler

### ISSUE THREAD

**Issue by gamma** [michitux/dokuwiki-plugin-move#22]
The "action_plugin_include" class wants a function "adaptRelativeId" with type "helper_plugin_move_handler" or leaves with errors.

**Comment by dryoo** [comment]
Me too~

**Comment by Juergen-aus-Koeln** [comment]
The page cannot be displayed any more. Instead of this there is a message
```
Fatal error: Error, handler function adaptRelativeId with 1 parameters called which isn't implemented in /opt/lampp/htdocs/wiki/lib/plugins/move/helper/handler.php on line 381
```

**Comment by michitux** [comment]
I have just fixed this in the include plugin, please update the include plugin. The include plugin should now work with both the old and the new move plugin.

**Comment by gamma** [comment]
Ok, thx. Can you please up the version on include to reflect the changes?

**Comment by michitux** [comment]
@gamma done, new version of the include plugin released, thx for the reminder.
