### ISSUE TITLE
Compatibility with release "Igor"?

### ISSUE THREAD

**Issue by j0hannes** [michitux/dokuwiki-plugin-move#223]
Hi,

Is this plugin compatible with the latest Dokuwiki release?

**Comment by splitbrain** [comment]
test it, update the compatibility info in the wiki

**Comment by splitbrain** [comment]
It's a wiki. We expect collaboration by users. I personally released over 100 plugins. I will not check each and every one for you.

If you use one of my plugins, go ahead and see if it breaks for you (it probably wont). If it does submit a bug report (or even better a PR). If not be nice to others (and me) and update the compatibility info.
