### ISSUE TITLE
The "Copy Page Plugin" has a better placement of the command "copy page"

### ISSUE THREAD

**Issue by schittli** [michitux/dokuwiki-plugin-move#225]
Hello

In DokuWiki, it would be great if the usability could be improved so that everything is more intuitive. 
In this context, I noticed that the "Copy page" plugin works much more intuitively because the command can be found next to the other page manipulation commands:

![image](https://user-images.githubusercontent.com/8282673/198155009-b094303a-c66d-468f-ade8-ae8f46b0215c.png)

I think it would be more useful if the `Move Page` (or `Rename Page`) command would be placed on this command bar, too.

Thanks a lot, kind regards,
Thomas

**Comment by splitbrain** [comment]
that's already the case. you might want to read the documentation.
