### ISSUE TITLE
Can't only create pages/media namespaces

### ISSUE THREAD

**Issue by eduardomozart** [michitux/dokuwiki-plugin-move#230]
I'm not sure if it's an intended behavior, but the plug-in allows to create a namespace when hovering the mouse through the "[Root namespace]" at Pages and Media files, but it's not possible only to create them. If I only create a new page/media namespace and click on "Start", the following error is shown:

````
There were no moves defined
````

**Comment by splitbrain** [comment]
empty namespaces are not a thing in DokuWiki. This is intended behaviour.
