### ISSUE TITLE
only move media files

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [michitux/dokuwiki-plugin-move#25]
Hi,

only moving media files without pages doesn't come to an end in the dialogue "Move in Progress..." although the files in fact are moved.

After cancelling, the page that is influenced by the media moves cannot be edited any more. Instead of this there is a message

**Fatal error**: Error, handler function adaptRelativeId with 1 parameters called which isn't implemented in /opt/lampp/htdocs/wiki/lib/plugins/move/helper/handler.php on line 381

The mentioned page contains commands of the include plugin and the qna plugin.

Regards
Juergen

**Comment by michitux** [comment]
Please update the include plugin, then editing the page should work again (this is issue #22). Maybe then also the move process ends again.

**Comment by Juergen-aus-Koeln** [comment]
Thank you very much, now it works as desired again

Regards Juergen
