### ISSUE TITLE
Warning: Trying to access array offset on value of type null in /home/.../wiki/lib/plugins/move/action/rename.php on line 42

### ISSUE THREAD

**Issue by DavWai** [michitux/dokuwiki-plugin-move#255]
This message appears when the page is open at first timme of the session.

Warning: Trying to access array offset on value of type null in /home/.../wiki/lib/plugins/move/action/rename.php on line 42

**Comment by kyjanond** [comment]
+1

**Comment by kianworld** [comment]
+1. Appears when I'm logged out.

**Comment by mboehn** [comment]
This is the same issue as in #256

**Comment by nicola-myo** [comment]
It can be resolved checking the null value of the array $USERINFO adding before the line 42:
<code>if (!is_null($USERINFO)) ...</code>
