### ISSUE TITLE
access array offset on value of type null

### ISSUE THREAD

**Issue by dregad** [michitux/dokuwiki-plugin-move#256]
Viewing any page when not authenticated (guest / anonymous) triggers

Warning: Trying to access array offset on value of type null in./dokuwiki/move/action/rename.php on line 42

`$INPUT->server->str('REMOTE_USER')` is not set when not authenticated... 

Regression introduced by 0af31bb63abd3731e904efc2ed90dd3ce33f4e52 (#246)

**Comment by nicola-myo** [comment]
It can be resolved checking the null value of the array $USERINFO adding before the line 42:
<code>if (!is_null($USERINFO)) ...</code>

**Comment by dregad** [comment]
I just submitted PR #275 to fix this annoying warning, @michitux hopefully you can merge it soon ?
