### ISSUE TITLE
Make fresh release after 2022-01-23

### ISSUE THREAD

**Issue by glensc** [michitux/dokuwiki-plugin-move#265]
There's quite a lot of changes since last tag:
- https://github.com/michitux/dokuwiki-plugin-move/compare/2022-01-23..8ba3be2eda0ebb92d8e61ec873172357acab2952

could the release tag be made so plugin manager would try to update it?

you may want to use this automation to ease releasing:
- https://github.com/dokuwiki/dokuwiki/issues/3951

(I'm willing to submit PR here of that if you ask me)

**Comment by michitux** [comment]
I've tagged a release and added the workflow (in the wrong order, so there is no release yet). Thank you! I would prefer having this workflow as part of the github-actions repository instead of some dokuwiki fork and the workflow logs some warnings, but I'm taking it as it is for now.
