### ISSUE TITLE
Rename pagetool not visible if used template isn't 'dokuwiki' or 'arago'

### ISSUE THREAD

**Issue by ohartl** [michitux/dokuwiki-plugin-move#27]
Had to fix this on my installation in /action/rename.php:45.
But why is the pagetool only displayed for these templates?

**Comment by borgendorf** [comment]
I'm also having this problem. I'm using a template called codowik and I don't see the rename icon anymore. I tried adding codowik to line 45 as above but nothing changed. Is there a way to make it work again?
