### ISSUE TITLE
outdated release tags

### ISSUE THREAD

**Issue by Zweihorn** [michitux/dokuwiki-plugin-move#277]
Please consider to **update the release tags** of this repository if possible.

Unfortunately, the current latest release information seems to be quite outdated and thus misleading as:
![Bildschirmfoto 2024-05-01 um 23 45 21](https://github.com/michitux/dokuwiki-plugin-move/assets/4863737/cb3214f6-1062-45ec-86ba-73b0181600f7)

I am aware this may not matter much for the update process as provided by DokuWiki. However, this could irritate visitors of this project and may be just bad for advertising the usefulness of this state of the art plug-in, I presume.

ref https://www.dokuwiki.org/plugin:move

Last not least a big thank you for your quite sustainable work and providing the 2024-04-26 update of this excellent plug-in. I find this plug-in both stable and quite useful and I just upgraded my own DokuWiki installations accordingly.

Keep on the good work and prosper.
🌻

**Comment by glensc** [comment]
I automate it in my projects with this shared workflow:
- https://github.com/dokuwiki/dokuwiki/pull/3966

example:
- https://github.com/glensc/dokuwiki-plugin-slacknotifier/blob/965547d96989413f04fbc102f2225438efb86bd7/.github/workflows/release.yml

**Comment by michitux** [comment]
I have added the workflow and manually marked the latest tag as release. In the future, this should be automatic now.
