### ISSUE TITLE
Conflict with updtable snippets plugin

### ISSUE THREAD

**Issue by turnermm** [michitux/dokuwiki-plugin-move#28]
One user has reported that there is a conflict with the Updatable snippets plugin:
https://github.com/turnermm/Updatable-Snippets-for-Dokuwiki/issues/5
Another user has reported a similar problem with snippets but has not said whether it is a conflict with move:
https://github.com/turnermm/Updatable-Snippets-for-Dokuwiki/issues/4
I haven't investigated yet myself.

**Comment by rnck** [comment]
That ([turnermm/Updatable-Snippets-for-Dokuwiki/issues/5](https://github.com/turnermm/Updatable-Snippets-for-Dokuwiki/issues/5)) was me.

As already described there, disabling the move plugin results in an working snippets plugin. Old version of the snippets plugin seems already affected by this bug.

What I found out in the meantime is, that the normal `<a class="wikilink1" ...` tags on the snippets popup page were not replaced as they should be. Here's a screenshot with move plugin enabled:
![snippets_move-enabled](https://cloud.githubusercontent.com/assets/165663/8338429/5bf1ed30-1ab1-11e5-85fa-077a4528d704.png)

and one with move plugin disabled:
![snippets_move-disabled](https://cloud.githubusercontent.com/assets/165663/8338455/80c4bc14-1ab1-11e5-8765-36c09704056f.png)

Please let me know if you need more info.

**Comment by michitux** [comment]
From what I understood, this seems to be fixed in the Updatable snippets plugin and can therefore be close. If not, please re-open or report a new issue.

**Comment by turnermm** [comment]
Yes, that was fixed.  Thanks.
