### ISSUE TITLE
fatal error triggered by info plugin in handler (as non real helper-component)

### ISSUE THREAD

**Issue by Klap-in** [michitux/dokuwiki-plugin-move#33]
This helper is not a real helper plugin component. Should it still have a getInfo() function?

```
PHP Fatal error:  Error, handler function getInfo with 0 parameters called which isn't implemented in /local/dokuwiki/dokuwiki/lib/plugins/move/helper/handler.php on line 381
```

**Comment by michitux** [comment]
I wonder how much work it would be to make this a real helper part and if this could cause any problems. We would probably need to replace the constructor by some initialization method as the plugin will then be constructed while it is loaded.
