### ISSUE TITLE
Installation Error in move/helper/rewrite.php

### ISSUE THREAD

**Issue by clemens-schlegel** [michitux/dokuwiki-plugin-move#35]
during installation this error comes up:

`Fatal error: require_once() [function.require]: Failed opening required '__DIR__/handler.php' (include_path='.:/usr/share/php') in /var/www/web87/html/EH/DokuWiki_EH/lib/plugins/move/helper/rewrite.php on line 14
`

what to do ?

**Comment by michitux** [comment]
Your PHP version is probably too old (< 5.3.0) such that `__DIR__` is not available yet. The current version of DokuWiki needs PHP 5.3.3. Therefore if you have the required PHP version this should work. Could you please check which PHP version you have?

**Comment by clemens-schlegel** [comment]
My PHP version is indeed 5.2.6. However, at the time of reporting the issue DokuWiki latest release "Hrun" was o.k. with PHP 5.2 (and works still fine).

**Comment by michitux** [comment]
You are right, "Hrun" still supports PHP 5.2, so adding a fix here makes sense. I hope the rest still works with PHP 5.2, please let me know if there should be any more issues.
