### ISSUE TITLE
Moving files only

### ISSUE THREAD

**Issue by stm-github** [michitux/dokuwiki-plugin-move#4]
Hi, 

I've just tested the move plugin on my wiki and stumbled across something. 

When I try to move a namespace (pages and files) to another one the plugin indicated that 1 page and 30 media files are supposed to be moved. But when trying to move only media files it indicates that 0 files are moved although I'm in the same namespace. Am I doing something wrong?

**Comment by michitux** [comment]
Probably this was/is a bug in the version of the move plugin you used, we have just released a massively changed and improved version. Please test if this is still an issue with the current version of the move plugin.

**Comment by splitbrain** [comment]
closing since no further feedback was given
