### ISSUE TITLE
Bogus labels in the move form with the last version of dokuwiki

### ISSUE THREAD

**Issue by npf** [michitux/dokuwiki-plugin-move#49]
Text labels are not shown.
All buttons display "admin" as label.

Dokuwiki 2015-08-10a "Detritus"

**Comment by tuudik** [comment]
I have same issue!
Does it affect somehow the functionality?

**Comment by tuudik** [comment]
Actually, I just uninstalled the plugin and then re-installed, and it started to work like a charm:)

**Comment by krichter722** [comment]
Same issue on 2015-08-10a "Detritus" as well.

> Actually, I just uninstalled the plugin and then re-installed, and it started to work like a charm:)

I can confirm that this works around the issue. Note that the re-install function of `dokuwiki` doesn't work.
![move_plugin_only_displays_admin_button_labels](https://cloud.githubusercontent.com/assets/4369372/12489644/9af420d2-c071-11e5-9d52-c2455888c53c.png)

**Comment by npf** [comment]
Sorry for not following up actively.
I upgraded today to dokuwiki 2016-06-26a and upgraded all the plugins: I don't see the issue any more.
Thanks
