### ISSUE TITLE
Not translated messages

### ISSUE THREAD

**Issue by Klap-in** [michitux/dokuwiki-plugin-move#5]
In the methods move_page() and move_media() are some untranslated messages:
e.g.:
  - `'Error while updating the search index '.$idx_msg`
  - `'The meta files of page '.$ID.' couldn\'t be moved'`
  - `'The attic files of page '.$ID.' couldn\'t be moved. Please move them manually.'`

Other possible improvement is adding a semicolon to the first string. That makes clear that $idx_msg is an additional message.
e.g.:
  - `'Error while updating the search index: '.$idx_msg`

Further there are some other untranslated strings.

**Comment by michitux** [comment]
Fixed by #13
