### ISSUE TITLE
media gets moved, but links are not updated

### ISSUE THREAD

**Issue by tmo26** [michitux/dokuwiki-plugin-move#52]
2015-08-10a "Detritus" / move plugin 2015-05-16

Problem: Media (pictures, jpgs) can be moved via the tree based move, but links to these media are not changed accordingly, despite the fact that the preview shows the link adjustment on the respective pages. "Adjust links after move" is checked. Purging the page cache doesn't help. There are no signs of link adjustment on the "recent edits" page. Only after manual link adjustment, the pictures are then shown again from their new location.

I was hoping to get around the manual re-linking by using the move plugin....

**Comment by michitux** [comment]
Did you make sure that the search index is up to date before starting the move? You can do this using the [searchindex](https://www.dokuwiki.org/plugin:searchindex) plugin or the [indexer.php](https://www.dokuwiki.org/cli#indexerphp) cli script if you have shell access on the server.

If this does not help, could you please provide a concrete example of a page that needs to be adjusted and the media move that did not trigger a change? Then maybe we can reproduce this (and create a test case which makes sure we do not break it again).

**Comment by tmo26** [comment]
Working before index rebuild: http://wiki.openwrt.org/toh/ubiquiti/routerstation.pro?do=diff&rev2[0]=1445068380&rev2[1]=1445098566&difftype=sidebyside

-> {{media...}} got updated.

To make sure that the index is up to date, I rebuilt the index now.

Working after index rebuild: http://wiki.openwrt.org/toh/actiontec/gt724wg?do=diff&rev2[0]=1445102946&rev2[1]=1445102979&difftype=sidebyside

Mind that only the link {{media...}} got updated.
The link {{:media...}} did not get updated, and that's the dominant variant in our wiki, since that's how the media manager creates image links.

**Comment by tmo26** [comment]
More indication that this is related to the ':'

Working (no ':' in front of the namespace): http://wiki.openwrt.org/toh/tp-link/tl-wa901nd?do=diff&rev2[0]=1445013815&rev2[1]=1445103671&difftype=sidebyside

Not working (':' in front of the namespace): http://wiki.openwrt.org/toh/tp-link/tl-wdr4900?do=revisions
I just renamed and moved an image, but no signs of link adaption by the move plugin.

**Comment by michitux** [comment]
That's strange as we have an explicit fix for this issue with the leading colon in the code which was definitely in the 2015-05-16 version, have a look at [this](https://github.com/michitux/dokuwiki-plugin-move/blob/2015-10-17/_test/mediamove.test.php#L67) test case. However what was definitely broken is adapting links that need to be cleaned. For example `{{my file.jpg}}` is a valid media link in DokuWiki. I've just pushed a fix for this issue, now media links are simply cleaned, too. Could you please test if this fixes the issue for you?

**Comment by tmo26** [comment]
Just updated and tested: Works!

Thanks for solving this iussue! :)
