### ISSUE TITLE
move doesn't work in animals

### ISSUE THREAD

**Issue by fthommen** [michitux/dokuwiki-plugin-move#53]
When installing the plugin in the farmer of a redirect farm, then it only works within the farmer.  In the animals the icon is different:
 
![move_plugin_icon_in_animals](https://cloud.githubusercontent.com/assets/279232/10250281/1aaec934-692a-11e5-8191-17cc8655cd04.png)

and clicking in the icon doesn't result in any action.

DokuWiki and all plugins are up-to-date.

**Comment by michitux** [comment]
I don't see how such a farm setup should impact things like displaying the icon. Could you please check if accessing the URL `/lib/plugins/move/images/sprite.png` works in your animal (prepend the base path of your animal)? Apart from that I don't see any reason of using a redirect farm, the official [farm setup](https://www.dokuwiki.org/farms) is actually simpler as some parts of what is still described in the page of the redirect farm is now directly included in DokuWiki itself. I have such a farm setup myself and in my animals the correct icon is displayed.

**Comment by fthommen** [comment]
On 17.10.15 13:13, Michael Hamann wrote:
> I don't see how such a farm setup should impact things like displaying
> the icon. Could you please check if accessing the URL
> |/lib/plugins/move/images/sprite.png| works in your animal (prepend the
> base path of your animal)? Apart from that I don't see any reason of
> using a redirect farm, the official farm setup
> <https://www.dokuwiki.org/farms> is actually simpler as some parts of
> what is still described in the page of the redirect farm is now directly
> included in DokuWiki itself. I have such a farm setup myself and in my
> animals the correct icon is displayed.

I cannot explain it, because I had reloaded the pages, restarted Apache, 
invalidated DokuWiki cache, cleared browser cache etc. etc. several 
times.  However when rechecking now, the plugin seems to work find in 
animals and the farmer.

I think this ticket can be closed and sorry for the fuss.

frank
