### ISSUE TITLE
Tree move : add checkbox option

### ISSUE THREAD

**Issue by Zatalyz** [michitux/dokuwiki-plugin-move#66]
Tree move is really good when I must move a lot of pages, but, if I have a lot of pages in the end of my list of pages, it's very hard to drag'n drop. I have a namespace with 600 entries, and my screen is not big enough to see all in once, so I use scrollbar and it's slow... 
With checbox, just "check" all the pages we want move, then select the namespace where we want to move them.
If we could use the drag'n drop OR checkbox, it would be wonderful, good for all :)

**Comment by StarArmy** [comment]
Yes! I am in a similar situation, having to move 600 files individually is killing my wrist.

**Comment by michitux** [comment]
Probably a bit too late for you, but I've just pushed some changes which implement a new drag & drop logic - and I also added checkboxes. They work as follows:

* Check as many pages and namespaces as you like
* Move one of the checked pages (or namespaces) to the destination

Note that the operation is aborted (i.e., nothing happens) when any of the moved items has a naming conflict or you try to move a namespace in itself (or a descendant of itself).

Do you think this is intuitive?

Still missing:
* check/uncheck all checkboxes
* select a range of pages (e.g. using `Shift`+`click`)

**Comment by Zatalyz** [comment]
Thanks a lot (with late) :) 

It seems very good. I don't have a lot of move to test it actually, but I'm sure it will be useful for lot of people.

Great work ! 👍
