### ISSUE TITLE
Page move not working, call to undefined function getRevisions()

### ISSUE THREAD

**Issue by mforkel** [michitux/dokuwiki-plugin-move#74]
When I try to move a page, a blank page is shown and the page is not moved. Each attempt seems to produce the following error:

`php[2864] 
   PHP Fatal error: Call to undefined function getRevisions() in C:\www\dokuwiki\lib\plugins\move\helper.php on line 402 
`

I'm running DokuWiki Elenor-of-Tsort 2016-06-26a with PHP 5.6.23. I had no problems with Detritus 2015-08-10a

**Comment by micgro42** [comment]
Please update your Move Plugin and see if that error goes away. #73 should have fixed it.

**Comment by mforkel** [comment]
Yes, that solved the problem. Thanks!

I noticed two things with the new interface:
 - The German translation "Vorschau der Änderungen" of "Preview changes"
is somewhat misleading. As there is no visual clue that itwill show a
list of actions, the user might be wondering why the list is empty,
mistaking the progress bar for an empty field. How about "Änderungen
anzeigen"?
 - After the page move, the wiki's start page is opened while I was
expecting the moved page


Am 14.07.2016 um 10:32 schrieb Michael Große:

**Comment by selivan** [comment]
I have latest release 2016-06-26 "Elenor Of Tsort". Had the same problem, but "update" button for Move plugin was not displayed. I uninstalled it and installed again, that fixed it. But update availability was not indicated in plugin manager. May be there is some trouble with plugin metadata, used by update manager.
