### ISSUE TITLE
Allow creation of new namespace in tree move

### ISSUE THREAD

**Issue by ysalmon** [michitux/dokuwiki-plugin-move#77]
I have been using this plugin for some years, albeit infrequently, with much satisfaction but for one very annoying point : I cannot create a new namespace in the tree move interface.

Is there a "profound" reason for this or is this just a problem with the interface itself ?
It is indeed possible to create a new namespace by moving one page into it.

It is cumbersome to have to use one interface to move the first page to the new namespace and then go to the tree interface to move the rest. But I have not yet found a workaround when the new namespace is intended to contain only media files.

I propose two solutions for an interface in the tree mode :
1. Use the rename interface and interpret e.g. `:newnamespace:oldname` as really meaning to move `oldname` under `:newnamespace` instead of escaping this input to `_newnamespace_oldname`.
2. In the tree view, add a `New namespace` node at each level, and again use the rename button to prompt for the name. The actual creation would be deferred until the global move operation is input to avoid creating empty namespaces.

**Comment by michitux** [comment]
This is an interface issue, there is no reason afaik. I also noticed that it seems to be impossible to move items back into a namespace once you emptied it using the tree move interface (without saving). The obvious workaround - inserting a ":" into the name - doesn't work, either.

**Comment by michitux** [comment]
This is also related to #17 - moving into empty namespaces does not work.

**Comment by michitux** [comment]
I've just pushed a new version that adds support for creating namespaces. I've just added a button to the root namespace similar to the "rename" button on other namespaces. This is definitely not the best UI, but it should work. It wouldn't be difficult to add such a button to every namespace but this would further clutter the UI. Any better ideas?

Note that the created namespaces themselves have no effect, i.e., they are not saved. However, whatever you move into them is renamed as expected (and you can also rename and move the created namespaces).

**Comment by ysalmon** [comment]
Thanks for this !

I do not think that the UI is cluttered ; not at all. The New namespace button, appearing only when mousing over the would-be-parent namespace, would not in my opinion make the UI less usable.
