### ISSUE TITLE
conflict with "siteexport" plugin: no links rewrite

### ISSUE THREAD

**Issue by flentus** [michitux/dokuwiki-plugin-move#81]
Under Release 2016-06-26a "Elenor of Tsort"
When both "siteexport" and "move" plugins are activated at the same time, when moving/renaming a file, links on pages pointing to this new name are not updated (checkbox "rewrite links" *is* checked).
Desactivating the "siteexport" plugin solves the issue.

Feel free to ask for more info.

Regards

**Comment by michitux** [comment]
The siteexport plugin re-defines the link syntax which breaks the move plugin. There are two fixes for this:
* The siteexport plugin can be easily fixed to not to capture all links but only those in the toc directly at handler level afaik (I would need to look up the exact way how that works in the handler). This should fix all links except those in a table of contents from the siteexport plugin.
* The move plugin can be adjusted to capture siteexport "links", too, and handle them like normal links (or alternatively the siteexport plugin could add move support)

The second fix alone should already fix the issue, the first one is mostly to make the plugin less intrusive.

**Comment by Jerk31** [comment]
I'm also encountering the same issue, could you please provide a quick fix for the 2nd solution? Thx :+1:

**Comment by michitux** [comment]
I've just forked the siteexport plugin and (hopefully) fixed this issue. You can find and test my fork [here](https://github.com/michitux/dokuwiki-plugin-siteexport/tree/move_support). Make sure you download the `move_support` branch (should be the case when you follow the button and download the ZIP). I've created a pull request and hope it will be merged soon (the plugin seems to be actively maintained, so I don't see any problem with that). If there should be any problems with that I could also integrate the code in the move plugin, I just don't want to add too much code that depends on the internals of other plugins.

**Comment by flentus** [comment]
Thankx a lot!
I'll test your fork and report ASAP if it fixes the issue and I see no side effects.

**Comment by Jerk31** [comment]
I've just tested it and it **works great** !! Thanks a lot for the fix, I've actually only added the "move.php" file in actions/ folder of the original plugin and it's fixed :)

**Comment by flentus** [comment]
Tested too (same as above: just added the "move.php" file to action directory): works great!

Thanks a lot for providing a qwick fix :-)

**Comment by michitux** [comment]
Note that my changes have been merged in the siteexport plugin, so when you install or update the plugin, you will get the fix automatically. I'm therefore closing this issue.
