### ISSUE TITLE
Support the struct plugin

### ISSUE THREAD

**Issue by psy-q** [michitux/dokuwiki-plugin-move#82]
Using a field of type "Page" in the [struct](https://www.dokuwiki.org/plugin:struct) plugin allows you to refer to one or multiple pages in the structured data of a page. However, when renaming a page using the move plugin, these pages inside the struct data are not renamed.

It would be nice if the move plugin could check pages for struct data and rename them accordingly. However, that would probably require working with the struct plugin's models and functions.

Update: I found out the support can also be done the other way round (from inside the struct plugin), and [there is a test for this over there](https://github.com/cosmocode/dokuwiki-plugin-struct/blob/master/_test/move.test.php). I managed to pretty quickly end up with dangling references between pages, so maybe the support is just not complete.

It looks like the struct plugin makes sure that any data entered for the page being moved is also moved, but it does not update references to the page being moved on other pages.

**Comment by splitbrain** [comment]
this has been fixed in the struct plugin and can be closed.

**Comment by psy-q** [comment]
Ah, you're right, sorry!
