### ISSUE TITLE
Relative page includes not updated correctly

### ISSUE THREAD

**Issue by ceriph** [michitux/dokuwiki-plugin-move#83]
When using page includes for example:

`{{page>.1:page_1&nofooter&noeditbutton}}`

The reference is only parsed correctly on namespace move if there is also a link to that page within the main page. Take this an example structure of:

wiki/old/namespace/main
wiki/old/namespace/1/page_1
wiki/old/namespace/1/page_2

Where the 'main' page content is:

```
====== Main ======

This is a test page

[[.1:page_1|link]]

{{page>.1:page_1&nofooter&noeditbutton}}

{{page>.1:page_2&nofooter&noeditbutton}}
```

When moving the namespace that this page and the referenced subpages are in, the result is:

```
====== Main ======

This is a test page

[[.1:page_1|link]]

{{page>.1:page_1&nofooter&noeditbutton}}

{{page>old:namespace:1:page_2&nofooter&noeditbutton}}
```

**Comment by michitux** [comment]
I cannot reproduce this. Is it possible that the index for the main page was not up to date? Or that moving page_2 failed? I've just added an additional test case to the include plugin with your example and it succeeds (see [travis build](https://travis-ci.org/dokufreaks/plugin-include/builds/188359283)).

**Comment by michitux** [comment]
Okay, I have a very different idea. Maybe this is a result of dokufreaks/plugin-include#103 - what kind of ACLs do you have, are these pages non-public? If yes, consider turning off the `safeindex` option of the inculde plugin and re-index the pages with the include syntax (visiting the pages should be enough, the include plugin makes sure pages are re-index when that option has been changed).

**Comment by ceriph** [comment]
Hi michtiux, thanks for the reply. I've just double checked and I'd be suprised if it was an ACL issue as I'm creating the test pages as mentioned above to reproduce the issue myself, all the pages are created in the same way and it's only the one that isn't linked that doesn't move correctly. However I'm happy to try that if you still think it's a potential cause.

It might also help if I clarify my exact steps just to make sure I'm not doing anything wrong:

- Create the main page `./old/namespace/main` as per above.
- Create `./old/namespace/1/page_1` and `./old/namespace/1/page_2`
- Navigate to the main page and see that the two includes are working
- Select Admin -> Move pages and namespaces
- Select Move namespace `old:namespace` and change to `new:namespace`
- Ignore errors is **unchecked** and Rewrite links is **checked**
- Press Start, then Start again
- I then navigate to the new location of main `./new/namespace/main`

It should be noted that `page_2` does get moved correctly, it's just the include in `main` isn't updated.

I suppose it could be an index issue, any ideas how I can verify the index?

**Comment by michitux** [comment]
If `./old/namespace/1/page_2` is non-public (i.e., is not accessible for the group `@ALL`) and the `safeindex` option of the include plugin is set, the include plugin won't create the necessary data for the index that is used by the move plugin. Links create that data regardless of the permissions, therefore having a link in addition to the include statement solves the problem. Note that it is only important that DokuWiki knows that the main page is somehow affected by moving page `./old/namespace/1/page_2`, it is not important which syntax on the page is affected.

**Comment by ceriph** [comment]
Excellent, disabling safeindex has indeed solved the problem! Since our wiki is fully internal I don't see a reason why I can't just leave this disabled. Many thanks for your help Michael.
