### ISSUE TITLE
New Feature - Add native recursive find & replace function to the Move Plugin

### ISSUE THREAD

**Issue by rgleason** [michitux/dokuwiki-plugin-move#88]
Develop an interface to use the find & replace functions so that a user can
Change the media directory to shorten it for example (by FTP Filezilla)
and then use 
Find:  "{{:opencpn:opencpn_user_manual.."  
Replace "{{:opencpn:user.." 
All files in Directory:  :opencpn:opencpn_user_manual    
and -recursively below [check]

For example.

**Comment by michitux** [comment]
So you suggest that it should be able to adjust links **without** moving any pages or media files?

Note that you can rename media directories using the admin plugin, e.g. using the tree-based move manager (the link can be found above the simple move manager) - and then also all links will be automatically adjusted.

**Comment by rgleason** [comment]
Did not know tree based move manager would adjust all links (inluding media and internal links ?).
The reason I am looking for this utility tool is I needed it badly during migration from Druple6 to redirect and verify links to pages, namespaces, titles, and images within the entire text. An easy search and replace tool within the native dokuwiki editor would continue to be very useful.

**Comment by rgleason** [comment]
- for maintenance.

**Comment by rgleason** [comment]
After thinking about this possible tool, and finally discovering that the Move Plugin and Move Manager will accomplish this:
_"All links to and from the pages that are moved will be updated to reflect the new location and/or name."_

It seems to me that many of the the operations for a good DW Edit or Move Plugin  "search" and "replace" of

1. media links
2. internal links
3. external links

as controlled and operated by an intelligent and knowledgeable Editor - "Manager" are already programmed in the Move Plugin.  Is there some way to make a text based 

1.  "search"
2.  "search" and "replace"

which will operate on the 

1.  Current page.
2.  Current namespace
3.  Current namespace and all below
4. Entire book or Namespace.

and has an "Undo" in case there is a mess up?

We would have used this tool extensively while migrating and it would have saved hours, as it was we had 8-10 guys editing the 480 pages that were migrated completely by hand.  I am very confident that such a tool would see continued use during ongoing maintenance!

**Comment by michitux** [comment]
The move plugin uses the search index of DokuWiki to find pages that contain links to moved pages or media files and then uses DokuWiki's parser to identify all links to pages or media files in the affected pages and changes them if necessary. Whenever a page is modified, a new revision of the page is created (but changes are batched, so when you move many pages e.g. using the tree-based move manager you should still only see 1-2 new revisions per affected page). In contrast to a simple search and replace this can identify much more complex situation e.g. when a link is `[[Foo Bar]]` it will be found if the page `foo_bar` is moved and using DokuWiki's parser makes sure that e.g. code blocks or special plugin syntax is not modified. Plugins can also add support, so e.g. the syntax of the include plugin will also be adjusted accordingly. I think it is therefore quite unlikely that there will be a major mess up. Individual pages can be easily reverted using the builtin revert functionality of DokuWiki.

External links are not indexed by DokuWiki and I believe this is also out of the scope of the move plugin (but it is not impossible, just slightly more difficult to implement). For links to pages and media files, mainly a user interface is missing. So as a summary what I understood so far what you would like to have is a four-step process:

1. Search for a link target (maybe also using a list of pages that are linked but do not exist)
2. Enter a new page/media id for the selected link target
3. A preview which pages might be affected, maybe even with a preview of the actual changes (on request, this is not very cheap to calculate) with the possibility to select which pages should actually be changed (or even on a per-link level which links should be changed).
4. Execute the changes.

And I guess an interface where this is possible for a larger amount of links all at once would also be useful. Is this correct so far?

I'm not sure this whole thing should be in the move plugin, but even if it should be a separate plugin it could make use of a lot of the functionality that is available in the move plugin.

I can definitely imagine that such a plugin could be useful, for example when you migrate data from another wiki or when you re-organize your wiki and split large pages that are referenced in a lot of places into parts. However, I don't see that I will create such a plugin/feature anytime soon.

**Comment by rgleason** [comment]
> Is this correct so far?  
Yes exactly.  Good points.

> Even if it should be a separate plugin it could make use of a lot of the functionality that is available in the move plugin.
Good!

> However,  I don't see that I will create such a plugin/feature anytime soon.
Yes, I understand why.... Perhaps knowing there is a good start, some other talented person will put their shoulder to the wheel...?

Thank you for your Plugin!

**Comment by rgleason** [comment]
What do you suggest I should I do with this very useful dialogue?  If I close it, it gets lost doesn't it?

**Comment by michitux** [comment]
I would leave it open as it is an open feature request. Closed issues are not lost, in the list of issues you can also choose to see closed issues - but they are far less visible of course.

**Comment by rgleason** [comment]
Michael,
I've added a paragraph with your answers to some questions to the Move Plugin
https://www.dokuwiki.org/plugin:move#technical_review_for_users

If you don't like what I've done you can remove it.

Rick

**Comment by splitbrain** [comment]
From what I understand, there's nothing in here that will or should be implemented in the move plugin. If there is, a new more focused issue should be opened.
