### ISSUE TITLE
New Feature - Make Move Plugin  optionally recursive

### ISSUE THREAD

**Issue by rgleason** [michitux/dokuwiki-plugin-move#89]
Add -recursive option with -interactive Yes/no   and Continue.

IMHO this should be a high priority otherwise user Editors will have to learn/know how to use UNIX, Find, Sed and also have access to the server!

See https://forum.dokuwiki.org/post/54788

**Comment by michitux** [comment]
What do you mean by recursive? Renaming namespaces is already possible and affects all pages below the namespace. Did I understand your forum post correctly that you want to be able to rename all pages with a certain name below a certain namespace to a different name? E.g. rename all pages "foo" to "bar" below namespace "ns1"?

**Comment by rgleason** [comment]
Sorry I was not clearer. To be able to move a namespace and all child namespaces and pages below that namespace would be a powerful tool for reorganizibg a wiki which does occur often during maintenance. 
I am sure there are repetative manual ways of doing this. Since we are migrating and checking links and syntax right now, have not beeded this so much.

However, when a page or namespace is moved are all the internal links in the document / book / parent namespace checked and changed with an option for user of yes/no showing the context of the link and the link itself?
I am sure there arw other housekeeping chores associated with " moving" such as media,  . What else is needed to have a clean move?
What happens to old  revisions and recent changes?

**Comment by rgleason** [comment]
I feel like a dunderhead right now. 

I finally found the controls for the Move Plugin and left this note on the Editor's page of our OpenCPN Dokuwiki.

"Administrators & Managers have access to Tools to Move pages & namespaces. Look under **Admin > Additional Plugins (bottom of page) > "Move Pages and Namespaces". Alternatively, there is then a link to the "Tree-based Move Manager" which is more graphic and is drag and drop. The documentation states "All links to and from the pages that are moved will be updated to reflect the new location and/or name." We have not used this plugin extensively while migrating the Drupal6 books.. Please use it carefully and check all links in the pages you move. Then report your experience under Summary of Progress for others to see. Thanks. "

Thank you so much for making this plugin. We look forward to using it!  I am sorry about my misunderstanding about what it does with links!

**Comment by michitux** [comment]
> However, when a page or namespace is moved are all the internal links in the document / book / parent namespace checked and changed with an option for user of yes/no showing the context of the link and the link itself?

Yes, all links should be adapted as you already noted (both relative links in the moved page as well as links to the moved page/media file). There is currently no such check feature. However, as the plugin is using DokuWiki's parser it should really only change links that actually point to the moved page/media file and nothing else. When a page is changed, a new revision is created so you can later inspect the changes and, if necessary, revert them.

> I am sure there arw other housekeeping chores associated with " moving" such as media, . What else is needed to have a clean move?

Both pages and media files have a list of revisions and saved, old versions in `attic`/`media_attic` respectively. These files need to be moved, too. Pages also have other metadata. Further, the search index needs to be adjusted (e.g. by re-indexing the page at the new location). The move plugin takes care of all that when you rename or move a page or media file. Depending on the plugins you are using there might be additional data to be moved. Plugins can add support for moving their data when a page is moved using the move plugin, e.g. the [struct](https://www.dokuwiki.org/plugin:struct) plugin adapts its database when a page is moved.

> What happens to old revisions and recent changes?

Old revisions are moved together with the page (and a new revision reflecting the move is added). In the recent changes, two changes are added, documenting both the deletion at the old name and the creation at the new name. As only one change per page is displayed in the recent changes, this means that older changes of the page won't be displayed in the recent changes.

**Comment by michitux** [comment]
The move plugin should leave the indexmenu syntax as it is as there is no special support for it (but due to using DokuWiki's parser the move plugin recognizes that the indexmenu syntax is plugin syntax and not e.g. a media link). What usually happens in the case of an incompatibility is that simply nothing is changed (see e.g. #81) - this is the case when plugins replace the original DokuWiki syntax. Further, I can imagine issues with some of the macros/automatic linking plugins (like [autolink2](https://www.dokuwiki.org/plugin:autolink2) which has an explicit conflict with the move plugin).

Feel free to improve the documentation to make clearer how the plugin works etc. - if you want you may also copy/adapt parts of what I wrote here. I'm sure the documentation can be improved, this whole link adjustment part is really not covered properly.

That recursive feature that you initially requested in this issue - is this still something you want or is what you imagined already covered by the move plugin? If it's not yet covered, please explain again what exactly is missing.

**Comment by rgleason** [comment]
I believe, the Move plugin has the recursive features I mentioned in the first post, with the exception of a step by step  Yes/No control. I am not sure if this is a needed feature yet or not. I need to use the plugin more.

Also, I believe my plugin was written with more of a "migration" mindset where it would be similar to "find" and "sed" but more integrated and useful to normal users.... Which is a different plugin that you have described, would use a lot of your work, but is an entirely different effort!

I hope I have been clear enough. Thanks again.

**Comment by rgleason** [comment]
PS can we leave these posts up for a little while so I can read the documentation and maybe add some of this?

**Comment by rgleason** [comment]
Michael,
I've added a paragraph with your answers to some questions to the Move Plugin
https://www.dokuwiki.org/plugin:move#technical_review_for_users

If you don't like what I've done you can remove it.

Rick

**Comment by splitbrain** [comment]
I rewrote parts of that to read more like a description and less like a copy/paste from a question/answer thread
