### ISSUE TITLE
Latest release leads to gateway error

### ISSUE THREAD

**Issue by tmo26** [michitux/dokuwiki-plugin-move#90]
2016-06-26a "Elenor of Tsort"

After installation of the latest release of the move plugin (2017-01-02), I get only a blank white screen.
Trying to access the wiki again leads to gateway error.

After removing the updated move plugin, the wiki is working normal again.

**Comment by michitux** [comment]
Which PHP version are you using? Did you use a previous version of the move plugin? How did you install the plugin (using the extension manager?)?

**Comment by michitux** [comment]
Another question: which template are you using? Where do you get the blank screen? Only when trying to access pages or also in the admin area?

**Comment by tmo26** [comment]
After the blank page event, I completely removed the plugin directory.
Now I re-installed the plugin to reproduce the issue - but the plugin installed perfectly, and the wiki is usable, unlike before. **Issue can be closed.**

To answer your questions:
- php_version	5.6.19-0+deb8u1
- previous version of move plugin was installed
- move plugin installed via extension manager
- template monobook
- blank screen appeared right after the plugin installation. The usual green bar "plugin successfully installed" did not show up. That was the only time the screen went completely blank.
- Accessing the startpage of the wiki lead to the mentioned gateway error
- Removing the move plugin made the wiki usable again
