### ISSUE TITLE
Multiple paint rollers in page footer with Starter template

### ISSUE THREAD

**Issue by mforkel** [michitux/dokuwiki-plugin-move#93]
In combination with the [Starter template](https://www.dokuwiki.org/template:starter), the new version 2017-01-07 of this plugin displays multiple paint rollers in the page footer. The previous version did not do that.

**Comment by polyzen** [comment]
https://ptpb.pw/jcVc.png

**Comment by michitux** [comment]
As a quick workaround you can disable the `pagetools_integration` configuration option of the move plugin. I'm not sure what the proper fix is - blacklist the starter template or maybe modify the CSS to not to add the icons for the starter template?

**Comment by mforkel** [comment]
Thanks michitux, disabling the option is good enough for me. Even though I miss the easy way to rename a page.
