### ISSUE TITLE
Tree Based Move

### ISSUE THREAD

**Issue by rgleason** [michitux/dokuwiki-plugin-move#96]
Why does it seem to only work two or three levels down?
Can't get below that because the item/line won't expand.  The 4-arrows come up on the cursor (trying to Move?) , changing from Hand, and  I cannot expand the directory.
Maybe there should be a single mode operation ie: Navigate  and then click something to go into the actual Move (4 arrows) mode?

Also the directories are not sorted in the order of indexmenu. either. but thats minor.

**Comment by Digitalin** [comment]
Same here ! 
Impossible to expand namespaces, tested with Firefox and Chromium.  Strangely, it works in local wiki I use to sync the wiki in prod. I don't see real differences as there are quite same (releases, contents, conf...), only few plugins more in the local wiki that I am testing. I just see some icons more just behind  names where there is the issue. (see image)

 
![move](https://cloud.githubusercontent.com/assets/12547689/22512996/16c2991c-e89b-11e6-852a-2c9988bc7f6f.png)

**Comment by rgleason** [comment]
I recently updated the plugin to the current version, and one user reports that the new ability to select multiple files is a great timesaver.  He is very happy with this improvement to select multiple files.
We will continue to work with Tree based move and report back here.

**Comment by rgleason** [comment]
It has been awhile since we updated the plugin and the new tree based move now has check boxes to select what is going to be moved.  We have found this to be very helpful.  You should also un-check the boxes after the move.  

I really appreciate that this feature was added so quickly because it saved use a whole lot of time and effort, and we will continue to use this feature a lot to keep our media libraries properly organized. (We have multiple editors that are learning and they inevitably get the media files landing in the wrong places!  Its hard to keep up with it and this Tree move really helps save time.

**Comment by michitux** [comment]
I think I decided not to un-check the boxes automatically as you might not be happy with the location where you dropped them and then might want to move the same set of items again. I guess having a simple box/button to un-check everything might be a good addition. I've added issue #104 for that.

Concerning the original issue: do you still have problems that items cannot be expanded? What I'm wondering if possibly the item you tried to expand was a page and not a namespace. From the screenshot @Digitalin attached it seems that possibly with some templates it is impossible to distinguish them. I've created issue #105 for investigating and fixing that.

**Comment by rgleason** [comment]
> I guess having a simple box/button to un-check everything might be a good addition. I've added issue #104 for that.   -

Great

>Wondering if possibly the item you tried to expand was a page and not a namespace. From the screenshot @Digitalin attached it seems that possibly with some templates it is impossible to distinguish them. I've created issue #105 for investigating and fixing that.

Yes.     This also an issue, but some namespaces required some clicks and waiting to open. I've started to get used to it.

**Comment by Digitalin** [comment]
About the original post, it was just for me a install problem and reinstall the plugin fixed it (rarely but sometime, it happens). 
I just open a [issue](https://github.com/LotarProject/dokuwiki-template-bootstrap3/issues/296) about how displays namespaces and pagenames with Bootstrap3 template.

**Comment by splitbrain** [comment]
closing this as the original issue seems to be fixed
